# Generated by Django 2.1.9 on 2019-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('TEXTIL', 'Textil'), ('CALZADO', 'Calzado'), ('COMPLEMENTOS', 'Complementos'), ('MAQUILLAJE', 'Maquillaje'), ('COSMETICA', 'Cosmética'), ('PERFUMERIA', 'Perfumería'), ('OTRO', 'Otro')], default='TEXTIL', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Mercado',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios', models.CharField(choices=[('FABRICACION', 'Fabricación, Confección, Packaging'), ('OBRAS', 'Obras, Logística, Almacén'), ('SOFTWARE', 'Software, Hardware, Comunicaciones'), ('GESTORIAS', 'Gestorías, Seguros, Abogados'), ('FINANCIACION', 'Financiación, Bancos'), ('MARKETING', 'Marketing, Eventos'), ('INFLUENCERS', 'Influencers, Ventas'), ('CONSULTORIA', 'Consultoría, Asesoramiento'), ('ASOCIACIONES', 'Asociaciones, Instituciones'), ('INFORMACION', 'Información, Noticias')], default='FABRICACION', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_eres', models.CharField(choices=[('MARCA', 'Marca'), ('ESPACIO', 'Espacios (Offline/Online)'), ('SERVICIO', 'Servicio')], default='MARCA', max_length=10)),
                ('que_buscas', models.CharField(choices=[('MARCA', 'Marca'), ('ESPACIO', 'Espacios (Offline/Online)'), ('SERVICIO', 'Servicio')], default='ESPACIO', max_length=10)),
                ('email', models.EmailField(max_length=80)),
                ('nombre', models.CharField(max_length=100)),
                ('mercado', models.ManyToManyField(to='landing.Mercado')),
                ('servicios', models.ManyToManyField(to='landing.Servicios')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('NIÑOS', 'Niños'), ('ADOLESCENTES', 'Adolescentes'), ('ADULTOS', 'Adultos')], default='MUJER', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Target',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='target',
            field=models.ManyToManyField(to='landing.Target'),
        ),
    ]
