# Generated by Django 2.1.9 on 2019-09-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('src', models.ImageField(blank=True, default='', upload_to='img/art/')),
                ('categoria', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='landing.Categoria')),
            ],
        ),
    ]
