# Generated by Django 2.1.9 on 2019-09-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='mercado',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='target',
        ),
        migrations.DeleteModel(
            name='Mercado',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
