# Generated by Django 2.1.9 on 2019-09-20 14:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190917_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(upload_to='img/about/')),
                ('imagen_2', models.ImageField(upload_to='img/about/')),
                ('imagen_3', models.ImageField(upload_to='img/about/')),
                ('sobre_mi', tinymce.models.HTMLField(default='Me llamo Paloma Ribeiro...', help_text="Este es el texto que aparece en la seccion 'Sobre mi'", max_length=15000)),
            ],
            options={
                'verbose_name_plural': 'Sobre mi',
            },
        ),
    ]
