# Generated by Django 2.1.9 on 2019-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagen_2',
            field=models.ImageField(blank=True, upload_to='img/about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagen_3',
            field=models.ImageField(blank=True, upload_to='img/about/'),
        ),
    ]
