# Generated by Django 2.1.9 on 2019-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='home',
            field=models.BooleanField(blank=True, default=False, help_text='Activala para que se muestre en la Home'),
        ),
    ]
