# Generated by Django 2.1.9 on 2019-09-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_imagen_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='home',
        ),
    ]
